// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nfionqljfnnugoiueknr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5maW9ucWxqZm5udWdvaXVla25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMDA2MjksImV4cCI6MjA3Nzc3NjYyOX0.Gt5FLugM_55pM8cAaD8GXMluVC_MuivFQBmHqPQzKso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);